import { useState } from 'react'
import './App.css'
import Modal from './components/Modal/Modal'
import Button from './components/Button/Button'
import detail_1 from '../src/assets/img/details_1.png';
import detail_2 from '../src/assets/img/details_2.png';
import detail_3 from '../src/assets/img/details_3.png';
import IMG from '../src/assets/img/d_go_logo.png';
import Carousel from './components/Carrusel/Carrusel';

function App() {





  const viewModal = () => setActiveModal((prev) => (true));
  const closeModal = () => setActiveModal((prev) => (false));
  
  
  const ARRAY_IMGS = [
    {
      img: detail_1,
      text: 'Internet 100% Fibra'
    },
    {
      img: detail_2,
      text: 'Velocidad Superior'
    },
    {
      img: detail_3,
      text: 'Internet Ilimitado'
    }
  ];
  
  const ARRAYS_CHILDRENS = [
    [
      [
        {
          title: 'Internet 100% Fibra',
          styleCard: { border: '1px solid #ff5a0a' },
          stylesMbps: { color: '#ff5a0a' },
          mbps: 200,
          mbpsLast: 100,
          promo: 'Duplica tu velocidad x3 meses',
          stylesPrice: { background: '#ff5a0a', border: '1px solid #ff5a0a' },
          price: 99,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 124,
          imgs: ARRAY_IMGS,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra',
          styleCard: { border: '1px solid #ff5a0a' },
          stylesMbps: { color: '#ff5a0a' },
          mbps: 300,
          mbpsLast: 150,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x3 meses',
          stylesPrice: { background: '#ff5a0a', border: '1px solid #ff5a0a' },
          price: 119,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 144,
          imgs: ARRAY_IMGS,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra',
          styleCard: { border: '1px solid #ff5a0a' },
          stylesMbps: { color: '#ff5a0a' },
          mbps: 400,
          mbpsLast: 200,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x3 meses',
          stylesPrice: { background: '#ff5a0a', border: '1px solid #ff5a0a' },
          price: 129,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 154,
          imgs: ARRAY_IMGS,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra',
          styleCard: { border: '1px solid #ff5a0a' },
          stylesMbps: { color: '#ff5a0a' },
          mbps: 600,
          mbpsLast: 300,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x3 meses',
          stylesPrice: { background: '#ff5a0a', border: '1px solid #ff5a0a' },
          price: 169,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 194,
          imgs: ARRAY_IMGS,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra',
          styleCard: { border: '1px solid #ff5a0a' },
          stylesMbps: { color: '#ff5a0a' },
          mbps: 600,
          mbpsLast: undefined,
          aditional: 'Incluye 2 Mesh + McAffe',
          promo: 'Duplica tu velocidad x2 meses',
          stylesPrice: { background: '#ff5a0a', border: '1px solid #ff5a0a' },
          price: 259,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 284,
          imgs: ARRAY_IMGS,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra',
          styleCard: { border: '1px solid #ff5a0a' },
          stylesMbps: { color: '#ff5a0a' },
          mbps: 1000,
          mbpsLast: undefined,
          aditional: 'Incluye 2 Mesh + McAffe',
          promo: 'Duplica tu velocidad x3 meses',
          stylesPrice: { background: '#ff5a0a', border: '1px solid #ff5a0a' },
          price: 459,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 484,
          imgs: ARRAY_IMGS,
          onClick: viewModal
        },
      ],
      [
        {
          title: 'Internet 100% Fibra + DGO Básico',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 200,
          mbpsLast: 100,
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 134,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 154,
          imgs: ARRAY_IMGS,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + DGO Básico',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 300,
          mbpsLast: 150,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 154,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 174,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + DGO Básico',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 400,
          mbpsLast: 200,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 164,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 184,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + DGO Básico',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 600,
          mbpsLast: 300,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 204,
          timePromo: 'Precio promo x6 meses',
          regularPrice: 224,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + DGO Básico',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 600,
          mbpsLast: undefined,
          aditional: 'Incluye 2 Mesh + McAffe',
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 294,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 314,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + DGO Básico',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 1000,
          mbpsLast: undefined,
          aditional: 'Incluye 2 Mesh + McAffe',
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 494,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 514,
          onClick: viewModal
        },
      ],
      [
        {
          title: 'Internet 100% Fibra + DGO Full',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 200,
          mbpsLast: 100,
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 156,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 176,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + DGO Full',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 300,
          mbpsLast: 150,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 176,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 196,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + DGO Full',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 400,
          mbpsLast: 200,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 186,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 206,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + DGO Full',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 600,
          mbpsLast: 300,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 226,
          timePromo: 'Precio promo x6 meses',
          regularPrice: 246,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + DGO Full',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 600,
          mbpsLast: undefined,
          aditional: 'Incluye 2 Mesh + McAffe',
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 316,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 336,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + DGO Full',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 1000,
          mbpsLast: undefined,
          aditional: 'Incluye 2 Mesh + McAffe',
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 516,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 536,
          onClick: viewModal
        },
      ],
    ],
    [
      [
        {
          title: 'Internet 100% Fibra',
          styleCard: { border: '1px solid #ff5a0a' },
          stylesMbps: { color: '#ff5a0a' },
          mbps: 200,
          mbpsLast: 100,
          promo: 'Duplica tu velocidad x3 meses',
          stylesPrice: { background: '#ff5a0a', border: '1px solid #ff5a0a' },
          price: 89,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 114,
          imgs: ARRAY_IMGS,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra',
          styleCard: { border: '1px solid #ff5a0a' },
          stylesMbps: { color: '#ff5a0a' },
          mbps: 300,
          mbpsLast: 150,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x3 meses',
          stylesPrice: { background: '#ff5a0a', border: '1px solid #ff5a0a' },
          price: 109,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 134,
          imgs: ARRAY_IMGS,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra',
          styleCard: { border: '1px solid #ff5a0a' },
          stylesMbps: { color: '#ff5a0a' },
          mbps: 400,
          mbpsLast: 200,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x3 meses',
          stylesPrice: { background: '#ff5a0a', border: '1px solid #ff5a0a' },
          price: 119,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 144,
          imgs: ARRAY_IMGS,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra',
          styleCard: { border: '1px solid #ff5a0a' },
          stylesMbps: { color: '#ff5a0a' },
          mbps: 600,
          mbpsLast: 300,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x3 meses',
          stylesPrice: { background: '#ff5a0a', border: '1px solid #ff5a0a' },
          price: 159,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 184,
          imgs: ARRAY_IMGS,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra',
          styleCard: { border: '1px solid #ff5a0a' },
          stylesMbps: { color: '#ff5a0a' },
          mbps: 600,
          mbpsLast: undefined,
          aditional: 'Incluye 2 Mesh + McAffe',
          promo: 'Duplica tu velocidad x2 meses',
          stylesPrice: { background: '#ff5a0a', border: '1px solid #ff5a0a' },
          price: 249,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 274,
          imgs: ARRAY_IMGS,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra',
          styleCard: { border: '1px solid #ff5a0a' },
          stylesMbps: { color: '#ff5a0a' },
          mbps: 1000,
          mbpsLast: undefined,
          aditional: 'Incluye 2 Mesh + McAffe',
          promo: 'Duplica tu velocidad x3 meses',
          stylesPrice: { background: '#ff5a0a', border: '1px solid #ff5a0a' },
          price: 449,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 474,
          imgs: ARRAY_IMGS,
          onClick: viewModal
        },
      ],
      [
        {
          title: 'Internet 100% Fibra + DGO Básico',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 200,
          mbpsLast: 100,
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 124,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 144,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + DGO Básico',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 300,
          mbpsLast: 150,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 144,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 164,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + DGO Básico',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 400,
          mbpsLast: 200,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 154,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 174,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + DGO Básico',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 600,
          mbpsLast: 300,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 194,
          timePromo: 'Precio promo x6 meses',
          regularPrice: 214,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + DGO Básico',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 600,
          mbpsLast: undefined,
          aditional: 'Incluye 2 Mesh + McAffe',
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 284,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 304,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + DGO Básico',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 1000,
          mbpsLast: undefined,
          aditional: 'Incluye 2 Mesh + McAffe',
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 484,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 504,
          onClick: viewModal
        },
      ],
      [
        {
          title: 'Internet 100% Fibra + DGO Full',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 200,
          mbpsLast: 100,
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 146,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 166,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + DGO Full',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 300,
          mbpsLast: 150,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 166,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 186,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + DGO Full',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 400,
          mbpsLast: 200,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 176,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 196,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + DGO Full',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 600,
          mbpsLast: 300,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 216,
          timePromo: 'Precio promo x6 meses',
          regularPrice: 236,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + DGO Full',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 600,
          mbpsLast: undefined,
          aditional: 'Incluye 2 Mesh + McAffe',
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 306,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 326,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + DGO Full',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 1000,
          mbpsLast: undefined,
          aditional: 'Incluye 2 Mesh + McAffe',
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 506,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 526,
          onClick: viewModal
        },
      ],
      [
        {
          title: 'Internet 100% Fibra + Fono WIN',
          styleCard: { border: '1px solid #ff5a0a' },
          stylesMbps: { color: '#ff5a0a' },
          mbps: 200,
          mbpsLast: 100,
          promo: 'Duplica tu velocidad x3 meses',
          stylesPrice: { background: '#ff5a0a', border: '1px solid #ff5a0a' },
          price: 89,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 109,
          imgs: ARRAY_IMGS,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + Fono WIN',
          styleCard: { border: '1px solid #ff5a0a' },
          stylesMbps: { color: '#ff5a0a' },
          mbps: 300,
          mbpsLast: 150,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x3 meses',
          stylesPrice: { background: '#ff5a0a', border: '1px solid #ff5a0a' },
          price: 109,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 129,
          imgs: ARRAY_IMGS,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + Fono WIN',
          styleCard: { border: '1px solid #ff5a0a' },
          stylesMbps: { color: '#ff5a0a' },
          mbps: 400,
          mbpsLast: 200,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x3 meses',
          stylesPrice: { background: '#ff5a0a', border: '1px solid #ff5a0a' },
          price: 119,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 139,
          imgs: ARRAY_IMGS,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + Fono WIN',
          styleCard: { border: '1px solid #ff5a0a' },
          stylesMbps: { color: '#ff5a0a' },
          mbps: 600,
          mbpsLast: 300,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x3 meses',
          stylesPrice: { background: '#ff5a0a', border: '1px solid #ff5a0a' },
          price: 159,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 179,
          imgs: ARRAY_IMGS,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + Fono WIN',
          styleCard: { border: '1px solid #ff5a0a' },
          stylesMbps: { color: '#ff5a0a' },
          mbps: 600,
          mbpsLast: undefined,
          aditional: 'Incluye 2 Mesh + McAffe',
          promo: 'Duplica tu velocidad x2 meses',
          stylesPrice: { background: '#ff5a0a', border: '1px solid #ff5a0a' },
          price: 249,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 269,
          imgs: ARRAY_IMGS,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + Fono WIN',
          styleCard: { border: '1px solid #ff5a0a' },
          stylesMbps: { color: '#ff5a0a' },
          mbps: 1000,
          mbpsLast: undefined,
          aditional: 'Incluye 2 Mesh + McAffe',
          promo: 'Duplica tu velocidad x3 meses',
          stylesPrice: { background: '#ff5a0a', border: '1px solid #ff5a0a' },
          price: 449,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 469,
          imgs: ARRAY_IMGS,
          onClick: viewModal
        },
      ],
    ],
    [
      [
        {
          title: 'Internet 100% Fibra',
          styleCard: { border: '1px solid #ff5a0a' },
          stylesMbps: { color: '#ff5a0a' },
          mbps: 200,
          mbpsLast: 100,
          promo: 'Duplica tu velocidad x3 meses',
          stylesPrice: { background: '#ff5a0a', border: '1px solid #ff5a0a' },
          price: 129,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 154,
          imgs: ARRAY_IMGS,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra',
          styleCard: { border: '1px solid #ff5a0a' },
          stylesMbps: { color: '#ff5a0a' },
          mbps: 300,
          mbpsLast: 150,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x3 meses',
          stylesPrice: { background: '#ff5a0a', border: '1px solid #ff5a0a' },
          price: 149,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 174,
          imgs: ARRAY_IMGS,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra',
          styleCard: { border: '1px solid #ff5a0a' },
          stylesMbps: { color: '#ff5a0a' },
          mbps: 400,
          mbpsLast: 200,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x3 meses',
          stylesPrice: { background: '#ff5a0a', border: '1px solid #ff5a0a' },
          price: 159,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 184,
          imgs: ARRAY_IMGS,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra',
          styleCard: { border: '1px solid #ff5a0a' },
          stylesMbps: { color: '#ff5a0a' },
          mbps: 600,
          mbpsLast: 300,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x3 meses',
          stylesPrice: { background: '#ff5a0a', border: '1px solid #ff5a0a' },
          price: 199,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 224,
          imgs: ARRAY_IMGS,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra',
          styleCard: { border: '1px solid #ff5a0a' },
          stylesMbps: { color: '#ff5a0a' },
          mbps: 600,
          mbpsLast: undefined,
          aditional: 'Incluye 2 Mesh + McAffe',
          promo: 'Duplica tu velocidad x2 meses',
          stylesPrice: { background: '#ff5a0a', border: '1px solid #ff5a0a' },
          price: 289,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 314,
          imgs: ARRAY_IMGS,
          onClick: viewModal
        },
      ],
      [
        {
          title: 'Internet 100% Fibra + DGO Básico',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 200,
          mbpsLast: 100,
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 164,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 184,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + DGO Básico',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 300,
          mbpsLast: 150,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 184,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 204,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + DGO Básico',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 400,
          mbpsLast: 200,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 194,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 214,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + DGO Básico',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 600,
          mbpsLast: 300,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 234,
          timePromo: 'Precio promo x6 meses',
          regularPrice: 254,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + DGO Básico',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 600,
          mbpsLast: undefined,
          aditional: 'Incluye 2 Mesh + McAffe',
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 324,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 344,
          onClick: viewModal
        },
      ],
      [
        {
          title: 'Internet 100% Fibra + DGO Full',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 200,
          mbpsLast: 100,
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 186,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 206,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + DGO Full',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 300,
          mbpsLast: 150,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 206,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 226,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + DGO Full',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 400,
          mbpsLast: 200,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 216,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 236,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + DGO Full',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 600,
          mbpsLast: 300,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 256,
          timePromo: 'Precio promo x6 meses',
          regularPrice: 276,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + DGO Full',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 600,
          mbpsLast: undefined,
          aditional: 'Incluye 2 Mesh + McAffe',
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 346,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 366,
          onClick: viewModal
        },
      ],
    ],
    [
      [
        {
          title: 'Internet 100% Fibra',
          styleCard: { border: '1px solid #ff5a0a' },
          stylesMbps: { color: '#ff5a0a' },
          mbps: 200,
          mbpsLast: 100,
          promo: 'Duplica tu velocidad x3 meses',
          stylesPrice: { background: '#ff5a0a', border: '1px solid #ff5a0a' },
          price: 119,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 144,
          imgs: ARRAY_IMGS,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra',
          styleCard: { border: '1px solid #ff5a0a' },
          stylesMbps: { color: '#ff5a0a' },
          mbps: 300,
          mbpsLast: 150,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x3 meses',
          stylesPrice: { background: '#ff5a0a', border: '1px solid #ff5a0a' },
          price: 139,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 164,
          imgs: ARRAY_IMGS,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra',
          styleCard: { border: '1px solid #ff5a0a' },
          stylesMbps: { color: '#ff5a0a' },
          mbps: 400,
          mbpsLast: 200,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x3 meses',
          stylesPrice: { background: '#ff5a0a', border: '1px solid #ff5a0a' },
          price: 149,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 174,
          imgs: ARRAY_IMGS,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra',
          styleCard: { border: '1px solid #ff5a0a' },
          stylesMbps: { color: '#ff5a0a' },
          mbps: 600,
          mbpsLast: 300,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x3 meses',
          stylesPrice: { background: '#ff5a0a', border: '1px solid #ff5a0a' },
          price: 189,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 214,
          imgs: ARRAY_IMGS,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra',
          styleCard: { border: '1px solid #ff5a0a' },
          stylesMbps: { color: '#ff5a0a' },
          mbps: 600,
          mbpsLast: undefined,
          aditional: 'Incluye 2 Mesh + McAffe',
          promo: 'Duplica tu velocidad x2 meses',
          stylesPrice: { background: '#ff5a0a', border: '1px solid #ff5a0a' },
          price: 279,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 304,
          imgs: ARRAY_IMGS,
          onClick: viewModal
        },
      ],
      [
        {
          title: 'Internet 100% Fibra + DGO Básico',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 200,
          mbpsLast: 100,
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 154,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 174,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + DGO Básico',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 300,
          mbpsLast: 150,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 174,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 194,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + DGO Básico',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 400,
          mbpsLast: 200,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 184,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 204,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + DGO Básico',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 600,
          mbpsLast: 300,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 224,
          timePromo: 'Precio promo x6 meses',
          regularPrice: 244,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + DGO Básico',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 600,
          mbpsLast: undefined,
          aditional: 'Incluye 2 Mesh + McAffe',
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 314,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 334,
          onClick: viewModal
        },
      ],
      [
        {
          title: 'Internet 100% Fibra + DGO Full',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 200,
          mbpsLast: 100,
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 176,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 196,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + DGO Full',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 300,
          mbpsLast: 150,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 196,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 216,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + DGO Full',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 400,
          mbpsLast: 200,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 206,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 226,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + DGO Full',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 600,
          mbpsLast: 300,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 246,
          timePromo: 'Precio promo x6 meses',
          regularPrice: 266,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra + DGO Full',
          styleCard: { border: '1px solid #26aae1' },
          stylesMbps: { color: '#26aae1' },
          mbps: 600,
          mbpsLast: undefined,
          aditional: 'Incluye 2 Mesh + McAffe',
          promo: 'Duplica tu velocidad x6 meses',
          img: IMG,
          stylesPrice: { background: '#26aae1', border: '1px solid #26aae1' },
          price: 336,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 356,
          onClick: viewModal
        },
      ],
      [
        {
          title: 'Internet 100% Fibra',
          styleCard: { border: '1px solid #ff5a0a' },
          stylesMbps: { color: '#ff5a0a' },
          mbps: 200,
          mbpsLast: 100,
          promo: 'Duplica tu velocidad x3 meses',
          stylesPrice: { background: '#ff5a0a', border: '1px solid #ff5a0a' },
          price: 119,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 139,
          imgs: ARRAY_IMGS,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra',
          styleCard: { border: '1px solid #ff5a0a' },
          stylesMbps: { color: '#ff5a0a' },
          mbps: 300,
          mbpsLast: 150,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x3 meses',
          stylesPrice: { background: '#ff5a0a', border: '1px solid #ff5a0a' },
          price: 139,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 159,
          imgs: ARRAY_IMGS,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra',
          styleCard: { border: '1px solid #ff5a0a' },
          stylesMbps: { color: '#ff5a0a' },
          mbps: 400,
          mbpsLast: 200,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x3 meses',
          stylesPrice: { background: '#ff5a0a', border: '1px solid #ff5a0a' },
          price: 149,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 169,
          imgs: ARRAY_IMGS,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra',
          styleCard: { border: '1px solid #ff5a0a' },
          stylesMbps: { color: '#ff5a0a' },
          mbps: 600,
          mbpsLast: 300,
          aditional: 'Incluye 1 Mesh',
          promo: 'Duplica tu velocidad x3 meses',
          stylesPrice: { background: '#ff5a0a', border: '1px solid #ff5a0a' },
          price: 189,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 209,
          imgs: ARRAY_IMGS,
          onClick: viewModal
        },
        {
          title: 'Internet 100% Fibra',
          styleCard: { border: '1px solid #ff5a0a' },
          stylesMbps: { color: '#ff5a0a' },
          mbps: 600,
          mbpsLast: undefined,
          aditional: 'Incluye 2 Mesh + McAffe',
          promo: 'Duplica tu velocidad x2 meses',
          stylesPrice: { background: '#ff5a0a', border: '1px solid #ff5a0a' },
          price: 279,
          timePromo: 'Precio promo x2 meses',
          regularPrice: 299,
          imgs: ARRAY_IMGS,
          onClick: viewModal
        },
      ],
    ],
  ];

  const[activeModal,setActiveModal]=useState(false)
  const [inputState, setInputState] = ('');
  const [selectedIndexSections, setSelectedIndexSections] = useState(0);
  const [selectedIndexSubSections, setSelectedIndexSubSections] = useState(0);
  const [slideCountCards, setSlideCountCards] = useState(ARRAYS_CHILDRENS[0][0].length);
  const [slideCards, setSlideCards] = useState(Array.from(Array(slideCountCards).keys()));
  const [childrens, setChildrens] = useState(ARRAYS_CHILDRENS[0][0]);
  const [numberCall, setNumberCall] = useState('(01) 6806775');
  const [tSource, setTSource] = useState(undefined);


  const OPTIONS_CARDS = {
    loop: false,
    slidesToScroll: 1,
    startIndex: 1,
  };



  return (
    <div className="App">

      <Button text='hello' onClick={viewModal}/>
      <Modal
            estado={activeModal}
            onclick={ closeModal }
        >
  <div className="container-carrusel"
      >
        <Carousel
          classNameSlide="embla__slide__trhee"
          slides={ slideCards }
          options={ OPTIONS_CARDS }
          haveButtons={ true }
          haveDots={ false }
          interval={ 0 }
          childrens={ childrens }
        />
      </div>
        </Modal>
    </div>
  )
}

export default App
